version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
    ignore: []

  - package-ecosystem: "npm"
    directory: "/apps/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 6
    labels:
      - "dependencies"
      - "frontend"

  - package-ecosystem: "npm"
    directory: "/packages/shared-utils"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 6
    labels:
      - "dependencies"
      - "packages"

  - package-ecosystem: "npm"
    directory: "/packages/shared-types"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 6
    labels:
      - "dependencies"
      - "packages"

  - package-ecosystem: "maven"
    directory: "/apps/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "backend"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"

# Optional global settings you can tune later:
# - `versioning-strategy` (increase/minor/patch/lockfile-only)
# - `allow`/`ignore` rules per update block
# - `assignees`, `reviewers`, `security-updates` toggles
