name: Backend CI
permissions:
  contents: read

on:
  push:
    paths:
      - "apps/backend/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    paths:
      - "apps/backend/**"

jobs:
  build-and-test-dev:
    runs-on: ubuntu-latest
    env:
      # Map dev secrets to the env vars Spring expects
      DATABASE_URL: ${{ secrets.DATABASE_URL_DEV }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME_DEV }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD_DEV }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build and run tests (dev profile)
        working-directory: apps/backend
        run: mvn -B -Dspring.profiles.active=dev -DskipITs=true verify


