name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - main
      - '**'
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: "github.event_name != 'pull_request'"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps (frontend)
        working-directory: apps/frontend
        run: npm ci

      - name: Build (frontend)
        working-directory: apps/frontend
        run: npm run build --if-present

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: apps/frontend
        run: |
          # If on main/master deploy to production
          if [ "${{ github.ref }}" = "refs/heads/main" ] || [ "${{ github.ref }}" = "refs/heads/master" ]; then
            vercel --prod --confirm
          else
            # For other branches, create a preview deployment
            vercel --confirm
          fi
